#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/pagestore
#
# IDENTIFICATION
#    src/backend/access/pagestore/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/pagestore
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	pagestore.o

include $(top_srcdir)/src/backend/common.mk
